# Generated by Django 2.0.13 on 2020-07-21 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OP', 'Operational'), ('TE', 'Temporary Error'), ('BR', 'Broken'), ('ND', 'Not Defined')], default='ND', max_length=2)),
                ('sensor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
