# Generated by Django 2.2.13 on 2020-11-23 02:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='신공학관', max_length=15)),
                ('levels', models.IntegerField()),
            ],
            options={
                'ordering': ['building_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('period', models.IntegerField(null=True)),
                ('sensor_type', models.CharField(choices=[('IG', 'Intergrated'), ('RD', 'Radar'), ('RF', 'RF'), ('UK', 'Unknown')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_num', models.CharField(default='1F', max_length=10)),
                ('img_file_path', models.CharField(default='/static/img/map_img/default.png', max_length=200)),
                ('building_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='logtable.Building')),
            ],
            options={
                'ordering': ['level_num'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logtable.Log')),
                ('fault_status', models.CharField(default='ND', max_length=2)),
                ('is_daily_reported', models.BooleanField(default='False')),
                ('is_reported', models.BooleanField(default='False')),
                ('is_handled', models.BooleanField(default='False')),
            ],
            bases=('logtable.log',),
        ),
        migrations.CreateModel(
            name='SME20U_Value',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logtable.Log')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('illum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rador', models.IntegerField()),
                ('last_movement_time', models.CharField(max_length=10)),
                ('co2', models.IntegerField()),
                ('tvoc', models.IntegerField()),
            ],
            bases=('logtable.log',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(default='DGU', max_length=10, unique=True)),
                ('sensor_status', models.CharField(choices=[('OP', 'Active'), ('TE', 'Error'), ('BR', 'Down'), ('ND', 'Unknown'), ('WN', 'Warning')], default='ND', max_length=2)),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fault_monitored', models.BooleanField(default='False')),
                ('position_x', models.FloatField(default='-1')),
                ('position_y', models.FloatField(default='-1')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.Level')),
                ('sensor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.DeviceModel')),
            ],
            options={
                'ordering': ['sensor_code'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='logtable.Sensor'),
        ),
    ]
