# Generated by Django 2.0.13 on 2020-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AlterField(
            model_name='log',
            name='sensor_name',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
