# Generated by Django 2.2.13 on 2020-08-04 07:41

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0001_initial'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('SELECT\n        row_number() over () as id,\n        sensor.sensor_name as Name,\n        sensor.sensor_code as Code,\n        log.updated_time as Updated_Time\n        FROM Log LEFT JOIN Sensor\n        ON sensor.sensor_code = log.sensor_id', 'LogView'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'LogView'),
            atomic=False,
        ),
    ]
