# Generated by Django 2.2.13 on 2020-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_fault_monitored',
            field=models.BooleanField(default='False'),
        ),
    ]
