# Generated by Django 2.2.13 on 2020-10-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='position_x',
            field=models.FloatField(default='-1'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='position_y',
            field=models.FloatField(default='-1'),
        ),
    ]
