# Generated by Django 2.2.13 on 2020-11-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0002_auto_20201027_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status',
            field=models.CharField(choices=[('OP', 'Operational'), ('TE', 'Temporary Error'), ('BR', 'Broken'), ('ND', 'Not Defined'), ('WN', 'Warning')], default='ND', max_length=2),
        ),
    ]
