# Generated by Django 2.2.13 on 2020-11-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0002_sensor_is_fault_monitored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status',
            field=models.CharField(choices=[('UP', 'Up'), ('ER', 'Error'), ('DW', 'Down'), ('UK', 'Unknown'), ('WN', 'Warning')], default='ND', max_length=2),
        ),
    ]
