# Generated by Django 2.0.13 on 2020-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0002_auto_20200721_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('levels', models.IntegerField()),
            ],
        ),
    ]
