# Generated by Django 2.2.13 on 2020-07-29 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0003_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_num', models.IntegerField()),
                ('img_file_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('IG', 'Intergration'), ('RD', 'Radar'), ('RF', 'RF')], max_length=2)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.Level')),
                ('sensor_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.Log')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.Building'),
        ),
        migrations.AddField(
            model_name='log',
            name='sensor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logtable.Sensor'),
            preserve_default=False,
        ),
    ]
