# Generated by Django 2.2.13 on 2020-11-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0003_auto_20201120_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status',
            field=models.CharField(choices=[('OP', 'Active'), ('TE', 'Error'), ('BR', 'Down'), ('ND', 'Unknown'), ('WN', 'Warning')], default='ND', max_length=2),
        ),
    ]
