# Generated by Django 2.2.13 on 2020-07-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0004_auto_20200729_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='logtable.Sensor'),
        ),
        migrations.AlterField(
            model_name='log',
            name='sensor_name',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
