# Generated by Django 2.2.13 on 2020-07-31 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0005_auto_20200731_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
        migrations.AddField(
            model_name='log',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtable.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_status',
            field=models.CharField(choices=[('OP', 'Operational'), ('TE', 'Temporary Error'), ('BR', 'Broken'), ('ND', 'Not Defined')], default='ND', max_length=2),
        ),
    ]
