# Generated by Django 2.2.13 on 2020-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0006_auto_20200731_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
