# Generated by Django 2.2.13 on 2020-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0007_auto_20200731_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
