# Generated by Django 2.2.13 on 2020-07-31 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logtable', '0008_auto_20200731_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='sensor_id',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
